name: Main Ci/CD
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
          echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "ğŸ” The name of branch is ${{ github.ref }} and repository is ${{ github.repository }}."
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
          echo "ğŸ–¥ï¸ The workflow is now ready to test code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Run tests
        run: |
          cd ${{ github.workspace }}/tests/install && ${{ github.workspace }}/tests/run-test-install.sh -c
      - run: echo "ğŸ This job's status is ${{ job.status }}."
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: lint
        uses: luke142367/Docker-Lint-Action@v1.1.1
        with:
          target: src/build/php/Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}